config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #homepage 
  root to: 'pages#home'

  #books 
 
    # get "/books", to: "books#index", as: "books"
    # get '/books/new',to: "books#new", as: "new_book"  
    # get '/books/:id/edit', to:"books#edit", as:"edit_book"
    # get "/books/:id", to: "books#show" ,as: "book"
    # delete "/books/:id", to: "books#destroy"
    # post '/books', to:"books#create" 
    # patch '/books/:id', to:"books#update"

  #authors 
  resources :authors do 
    resources :books
end


  
    # get "/authors" , to: "authors#index"
    # get '/authors/new',to: "authors#new", as: "new_author" 
    # get "/authors/:id", to: "authors#show" ,as: "author"
    # delete "/authors/:id" , to:"authors#destroy"
    # post '/authors', to:"authors#create" 
    # get "/authors/:id/edit" , to:"authors#edit" , as: "edit_author"
    # patch "/authors/:id" , to:"authors#update" 
   
  
  #patients
  resources :patients
    # get "/patients" , to:"patients#index", as: "patients"
    # get '/patients/new',to: "patients#new", as: "new_patient" 
    # get "/patients/:id" , to:"patients#show" , as:"patient"
    # post '/patients' , to:"patients#create"
    # delete "/patients/:id" , to:"patients#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author      
end

app/models/patient.rb
class Patient < ApplicationRecord

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController 

    def index
        @authors=Author.all
     end

    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
     end
     def create
        @author = Author.create(author_params)
        redirect_to authors_path(@author)
     end

     def destroy
        @author = Author.find(params[:id])
        @author.destroy
        
        redirect_to authors_path
     end


     def edit
        @author = Author.find(params[:id])
     end

     def update
        @author = Author.find(params[:id])
        @author.update(author_params)
        redirect_to authors_path(@author)
        
     end

     def author_params
        params.require(:author).permit(:First_name, :Last_name ,:nickname , :hometown , :age)
     end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @author = Author.find(params[:author_id])
        @books = @author.books
    end

    def show 
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
    end

    def destroy
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
        @book.destroy

        redirect_to author_books_path(@author)
    end

    def new 
        @author = Author.find(params[:author_id])
        @book = @author.books.new
    end

    def create
        @author = Author.find(params[:author_id])
        @book = @author.books.create(book_params)
        # redirect_to books_path
        redirect_to author_book_path(@author, @book)
    end

    def edit 
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
    end

    def update 
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
        @book.update(book_params)
        # redirect_to books_path
        redirect_to author_book_path(@author, @book)
    end

    def book_params
        params.require(:book).permit(:title, :print_date, :original_language)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController 

    def index
        @patients =Patient.all
    end
    def new
        @patient =Patient.new
    end
    def show
        @patient = Patient.find(params[:id])
    end
    def create
        @patient = Patient.create(patient_params)
        redirect_to patients_path(@patient)
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy
        
        redirect_to patients_path
    end


    def patient_params
        params.require(:patient).permit(:first_name, :last_name , :diagnosis , :born_on)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<%= form_for @author, url: {action: "update"} do |f| %>
    <h4> First name </h4>
    <%= f.text_field :First_name %>
    <h4> Last name </h4>
    <%= f.text_field :Last_name %>
    <h4> Nickname </h4>
    <%= f.text_field :nickname %>
    <h4> HomeTown </h4>
    <%= f.text_field :hometown %>
    <h4> Age </h4>
    <%= f.text_field :age%>

    
    <%= f.submit "Save" %>
<% end %>

app/views/authors/index.html.erb
<h1> Authors List </h1> 
<%= link_to 'Create a Author' , new_author_path %>

 <% @authors.each do |author|%>

<h3> <%= author.First_name %> <%= author.Last_name %>  {<%= author.nickname %> } </h3>


<% end %>

app/views/authors/new.html.erb
<%= form_for @author, url: {action: "create"} do |f| %>

    <h4> First name </h4>
    <%= f.text_field :First_name %>
    <h4> Last name </h4>
    <%= f.text_field :Last_name %>
    <h4> Nickname </h4>
    <%= f.text_field :nickname %>
    <h4> HomeTown </h4>
    <%= f.text_field :hometown %>
    <h4> Age </h4>
    <%= f.number_field :age%>
    
    <%= f.submit "Save" %>
<% end %>

app/views/authors/show.html.erb
<p> <%= link_to "Back", authors_path %> </p> 

<h1> First Name :  <%= @author.First_name %> </h1>
<p> Last Name : <%= @author.Last_name %> </p>
<p> Nickname : <%= @author.nickname %> </p>
<p> Hometown : <%= @author.hometown %> </p>
<p> Age : <%= @author.age %> </p>

<p> <%= link_to 'View Books', author_books_path(@author) %> </p>


<%= link_to "edit" , edit_author_path(@author) %>
<p> <%= link_to "Delete Author" , author_path(@author), method: :delete %></p>

app/views/books/edit.html.erb
<%= form_for @book, url: {action: "update"} do |f| %>
    <h3> Title Of Book</h3>
    <%= f.text_field :title %>
    <h3> Print Date</h3>
    <%= f.date_field :print_date %>
    <h3> Original Language</h3>
    <%= f.text_field :original_language %>


    
    <%= f.submit "Save" %>
<% end %>

app/views/books/index.html.erb
<p> <%= link_to "Back", author_path(@author) %> </p>

<h1><%=@author.First_name %>'s Books</h1>

<h2>
    <%= link_to 'Create a book', new_author_book_path(@author) %>
</h2>

<% @books.each do |book| %>

    <h3>
        <%= link_to book.title, author_book_path(@author, book) %>
    </h3>

<% end %>

app/views/books/new.html.erb
<%= form_for @book, url: {action: "create"} do |f| %>

    <h3> Title Of Book</h3>
    <%= f.text_field :title %>
    <h3> Print Date</h3>
    <%= f.date_field :print_date %>
    <h3> Original Language</h3>
    <%= f.text_field :original_language %>

    

    
    <%= f.submit "Save" %>
    
<% end %>

app/views/books/show.html.erb
<p> <%= link_to "Back", author_books_path(@author) %> </p>
<h1>
    <%= @book.title %>
    <%= @book.print_date %>
    <%= @book.original_language %>
</h1>

<p>
<%= link_to 'Edit', edit_author_book_path(@author, @book) %>
<%= link_to 'Destroy this book!', author_book_path(@author, @book), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello, Rails!</h1>
<h2>
<%= link_to 'Patients', controller: 'patients' %>

<%= link_to 'Books', controller: 'books' %>

<%= link_to 'Authors', controller: 'authors' %>
</h2>

app/views/patients/index.html.erb
<h1> patients </h1>
<%= link_to 'Add a patient' , new_patient_path %>
<% @patients.each do |patient|%>

    <h3> <%= patient.first_name %>  <%= patient.last_name %> </h3>
    
    <p> <%= patient.diagnosis %> <%= patient.born_on %>   </p>
  
    
    <% end %>

app/views/patients/new.html.erb
<%= form_for @patient, url: {action: "create"} do |f| %>
    <h6> First Name</h6>
    <%= f.text_field :first_name %>
    <h6>Last Name</h6>
    <%= f.text_field :last_name %>
    <h6>Diagnosis</h6>
    <%= f.text_field :diagnosis %>
    <h6>Born on</h6>
    <%= f.date_field :born_on %>
     <br>
    <%= f.submit "Save" %>
<% end %>

app/views/patients/show.html.erb
<h3> <%= @patient.first_name %>   <%= @patient.last_name %>  </h3>

<p> <%= @patient.diagnosis %> <%= @patient.born_on %>   </h3>

<p> <%= link_to "Delete Patient" , patient_path(@patient), method: :delete %></p>